# Generated by Django 5.2.6 on 2026-01-18 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('books', 'Books'), ('fashion', 'Fashion & Accessories'), ('home', 'Home & Living'), ('sports', 'Sports & Outdoors'), ('beauty', 'Beauty & Personal Care'), ('toys', 'Toys & Games'), ('food', 'Food & Beverages'), ('experience', 'Experiences'), ('other', 'Other')], max_length=20)),
                ('price_range', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gift_images/')),
                ('product_url', models.URLField(blank=True)),
                ('age_group', models.CharField(blank=True, max_length=20)),
                ('gender_preference', models.CharField(blank=True, max_length=10)),
                ('interests', models.JSONField(default=list)),
                ('popularity_score', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gift Suggestion',
                'verbose_name_plural': 'Gift Suggestions',
                'ordering': ['-popularity_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('occasion', models.CharField(choices=[('birthday', 'Birthday'), ('milestone', 'Milestone Birthday'), ('belated', 'Belated Birthday'), ('surprise', 'Surprise Birthday')], default='birthday', max_length=20)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('is_premium', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-usage_count', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('reminder_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_reminder_sent', models.BooleanField(default=False)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishes.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GroupWish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('scheduled_send_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('invitation_code', models.CharField(max_length=12, unique=True)),
                ('allow_anonymous_contributions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_wishes_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_wishes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Wish',
                'verbose_name_plural': 'Group Wishes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupWishContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True)),
                ('voice_message', models.FileField(blank=True, null=True, upload_to='group_voice_messages/')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='wishes.groupwish')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('group_wish', 'contributor')},
            },
        ),
        migrations.AddField(
            model_name='groupwish',
            name='contributors',
            field=models.ManyToManyField(related_name='contributed_wishes', through='wishes.GroupWishContribution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BirthdayWish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wish_type', models.CharField(choices=[('text', 'Text Message'), ('voice', 'Voice Message'), ('video', 'Video Message'), ('card', 'Digital Card'), ('group', 'Group Wish')], default='text', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('text_content', models.TextField(blank=True)),
                ('voice_message', models.FileField(blank=True, null=True, upload_to='voice_messages/')),
                ('video_message', models.FileField(blank=True, null=True, upload_to='video_messages/')),
                ('card_template', models.CharField(blank=True, max_length=50)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('likes_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_wishes', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_wishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Birthday Wish',
                'verbose_name_plural': 'Birthday Wishes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='wishes_birt_recipie_fea193_idx'), models.Index(fields=['scheduled_date'], name='wishes_birt_schedul_9ecf74_idx')],
            },
        ),
    ]
